Vagrant.configure("2") do |config|
  
  config.vm.define :jenkins do |jenkinslts|
    jenkinslts.vm.box = "ubuntu/xenial64"
	jenkinslts.vm.network "private_network", ip: "192.168.33.17"
	
	jenkinslts.vm.provision "shell", inline: <<-SHELL
		apt-get update
		sudo apt-get install \
			apt-transport-https \
			ca-certificates \
			curl \
			software-properties-common -y
		
		curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
		
		sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu	$(lsb_release -cs) stable"
		sudo apt-get update -y 
		sudo apt-get install docker-ce -y
		#390f3e7bc0a544faa9d17887d26906c1
		sudo docker pull jenkins/jenkins:lts
	  SHELL
  end
  
  config.vm.define :coreslave do |coreslave|
	coreslave.vm.box = "StefanScherer/windows_2016_docker"

	coreslave.vm.network "private_network", ip: "192.168.33.15"

	coreslave.vm.provider "virtualbox" do |vb|
		 vb.gui = true
		 vb.memory = "4096"
		 vb.cpus = 4
	  end

	coreslave.vm.provision:"provisioner_dev", type: :shell, path: "scripts/install_all.ps1"
	  
	coreslave.vm.boot_timeout = 600
	coreslave.winrm.password="vagrant" 
	coreslave.winrm.username="vagrant"
	coreslave.vm.communicator = "winrm"
  end
 end

