# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define :eqCli do |eqCli|
    eqCli.vm.box = "AndrewDryga/vagrant-box-osx"
    #eqCli.vm.network :private_network, ip: "192.168.33.11"
    #eqCli.vm.hostname = "eqCli"
	
  end
  #config.vm.define :eqServer do |eqServer|
  #  eqServer.vm.box = "burkex/win-2012r2-std-sqlexpr"
  #  eqServer.vm.network :private_network, ip: "192.168.33.10"
  #  eqServer.vm.hostname = "eqServer"
#	eqServer.vm.communicator = "winrm"
 # end
  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     #vb.customize ["modifyvm", :id, "--vram", "40"]	
#	 vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']    
     
     vb.memory = "4096"
  end
 
end
 
