winget install -e --id Microsoft.VisualStudioCode
winget install JanDeDobbeleer.OhMyPosh -s winget
winget install Microsoft.PowerShell -s winget
winget install GitHub.cli -s winget
winget install Docker.DockerDesktop -s winget
winget install notepadplusplus -s winget
winget install dbeaver.dbeaver -s winget
winget install Postman.Postman -s winget
winget install Ghisler.TotalCommander -s winget
winget install Microsoft.Azure.StorageExplorer -s winget
winget install WiresharkFoundation.Wireshark -s winget
winget install JetBrains.IntelliJIDEA.Community -s winget
winget install GNU.MidnightCommander -s winget